INSERT INTO roles (rol, descripcion) VALUES
('Admin', 'Developers.'),
('Veterinario', 'Usuario veterinario matriculado.'),
('Propietario', 'Usuario dueño de mascota.');

INSERT INTO categorias_matriculas (id, categoria, cobertura) VALUES 
('A', 'ACTIVO A', 'Veterinarios en el ejercicio general e independiente de la profesión (clínicas privadas, consultorías y comercio veterinario general).'),
('B', 'ACTIVO B', 'Veterinarios con cargos electivos o de relación de dependencia exclusiva en organismos públicos nacionales (Ej. SENASA, universidades nacionales). El pago de su matrícula es optativo.'),
('C', 'ACTIVO C', 'Profesionales con matrícula activa pero bajo modalidades restrictivas específicas (roles corporativos internos, tareas puramente administrativas no clínicas o regímenes especiales).');

INSERT INTO diagnosticos_atencion (diagnostico, categoria) VALUES
-- Dermatología
('Otitis Externa', 'Dermatología'),
('Dermatitis Alérgica por Picadura de Pulga (DAPP)', 'Dermatología'),
('Atopia / Dermatitis Alérgica Ambiental', 'Dermatología'),
('Pioderma Superficial Bacteriano', 'Dermatología'),
('Demodiciosis (Sarna Demodéctica)', 'Dermatología'),
('Sarna Sarcóptica', 'Dermatología'),
('Dermatofitosis (Tiña)', 'Dermatología'),
('Dermatitis por Malassezia', 'Dermatología'),

-- Gastroenterología
('Gastroenteritis Aguda Inespecífica', 'Gastroenterología'),
('Parvovirosis Canina', 'Gastroenterología'),
('Pancreatitis Aguda', 'Gastroenterología'),
('Enfermedad Inflamatoria Intestinal (IBD)', 'Gastroenterología'),
('Lipidosis Hepática Felina', 'Gastroenterología'),
('Gastritis Crónica', 'Gastroenterología'),
('Colitis Aguda', 'Gastroenterología'),

-- Parasitología (Sistémica e Interna)
('Parasitosis Gastrointestinal (Nematodos/Cestodos)', 'Parasitología'),
('Giardiasis', 'Parasitología'),
('Coccidiosis', 'Parasitología'),
('Erliquiosis Canina (Ehrlichia canis)', 'Parasitología'),
('Anaplasmosis', 'Parasitología'),
('Leishmaniosis Canina', 'Parasitología'),
('Dirofilariosis (Gusano del corazón)', 'Parasitología'),

-- Urología y Nefrología
('Infección del Tracto Urinario Inferior (ITU)', 'Urología / Nefrología'),
('Enfermedad Renal Crónica (ERC)', 'Urología / Nefrología'),
('Insuficiencia Renal Aguda (IRA)', 'Urología / Nefrología'),
('Enfermedad del Tracto Urinario Inferior Felino (FLUTD)', 'Urología / Nefrología'),
('Urolitiasis (Cálculos Urinarios)', 'Urología / Nefrología'),
('Cistitis Idiopática Felina (CIF)', 'Urología / Nefrología'),

-- Enfermedades Infecciosas y Sistémicas
('Moquillo Canino (Distemper)', 'Infecciosas / Sistémicas'),
('Complejo Respiratorio Felino (Rinotraqueítis/Calicivirus)', 'Infecciosas / Sistémicas'),
('Leucemia Felina (ViLeF)', 'Infecciosas / Sistémicas'),
('Inmunodeficiencia Felina (VIF)', 'Infecciosas / Sistémicas'),
('Peritonitis Infecciosa Felina (PIF)', 'Infecciosas / Sistémicas'),
('Toxoplasmosis', 'Infecciosas / Sistémicas'),

-- Respiratorio
('Traqueobronquitis Infecciosa Canina (Tos de las Perreras)', 'Respiratorio'),
('Asma Felino / Bronquitis Crónica', 'Respiratorio'),
('Neumonía Bacteriana', 'Respiratorio'),
('Colapso Traqueal', 'Respiratorio'),

-- Endocrinología
('Diabetes Mellitus', 'Endocrinología'),
('Hipertiroidismo Felino', 'Endocrinología'),
('Hipotiroidismo Canino', 'Endocrinología'),
('Hiperadrenocorticismo (Síndrome de Cushing)', 'Endocrinología'),

-- Cardiología
('Enfermedad Mixomatosa de la Válvula Mitral (Endocardiosis)', 'Cardiología'),
('Cardiomiopatía Hipertrófica Felina (CMH)', 'Cardiología'),
('Cardiomiopatía Dilatada Canina (CMD)', 'Cardiología'),
('Insuficiencia Cardíaca Congestiva (ICC)', 'Cardiología'),

-- Oftalmología
('Conjuntivitis Infecciosa', 'Oftalmología'),
('Úlcera Corneal Superficial', 'Oftalmología'),
('Queratoconjuntivitis Seca (Ojo Seco)', 'Oftalmología'),
('Glaucoma', 'Oftalmología'),
('Cataratas', 'Oftalmología'),

-- Traumatología y Ortopedia
('Osteoartritis Crónica / Artrosis', 'Traumatología y Ortopedia'),
('Displasia de Cadera', 'Traumatología y Ortopedia'),
('Rotura del Ligamento Cruzado Anterior (LCA)', 'Traumatología y Ortopedia'),
('Luxación de Patela', 'Traumatología y Ortopedia'),
('Fractura Ósea por Traumatismo', 'Traumatología y Ortopedia'),

-- Oncología
('Linfoma Multicéntrico', 'Oncología'),
('Tumor de Mama / Neoplasia Mamaria', 'Oncología'),
('Mastocitoma', 'Oncología'),

-- Preventivo / Clínico General (Para cerrar consultas sin patologías)
('Paciente Sano / Control de Rutina', 'Preventivo / General'),
('Evaluación Pre-quirúrgica', 'Preventivo / General'),
('Control Post-operatorio', 'Preventivo / General');

INSERT INTO especies (especie) VALUES
('Canino'),
('Felino');

INSERT INTO razas (especie_id, raza) VALUES 
(1, 'Mestizo / Criollo'),
(1, 'Raza No Identificada / Otra'),
(1, 'Affenpinscher'), 
(1, 'Perro Africano'), 
(1, 'Airedale Terrier'), 
(1, 'Akita'), 
(1, 'Boyero de Appenzell'), 
(1, 'Pastor Australiano'), 
(1, 'Basenji'), 
(1, 'Basset Hound'), 
(1, 'Beagle'), 
(1, 'Coonhound Azul'), 
(1, 'Borzoi'), 
(1, 'Boyero de Flandes'), 
(1, 'Boxer'), 
(1, 'Brabanzón'), 
(1, 'Pastor de Brie'), 
(1, 'Buhund Noruego'), 
(1, 'Boston Terrier'), 
(1, 'Bulldog Inglés'), 
(1, 'Bulldog Francés'), 
(1, 'Staffordshire Bull Terrier'), 
(1, 'Cairn Terrier'), 
(1, 'Pastor Ganadero Australiano'), 
(1, 'Cavapoo'), 
(1, 'Chihuahua'), 
(1, 'Chow Chow'), 
(1, 'Clumber Spaniel'), 
(1, 'Cockapoo'), 
(1, 'Border Collie'), 
(1, 'Coonhound'), 
(1, 'Corgi Cardigan'), 
(1, 'Cotón de Tuléar'), 
(1, 'Salchicha / Dachshund'), 
(1, 'Dálmata'), 
(1, 'Gran Danés'), 
(1, 'Lebrel Escocés'), 
(1, 'Dhole'), 
(1, 'Dingo'), 
(1, 'Doberman'), 
(1, 'Cazador de Alces Noruego'), 
(1, 'Boyero de Entlebucher'), 
(1, 'Esquimal'), 
(1, 'Lapón Finlandés'), 
(1, 'Bichón Frisé'), 
(1, 'Pastor Alemán'), 
(1, 'Goldendoodle'), 
(1, 'Galgo Italiano'), 
(1, 'Groenendael'), 
(1, 'Habanero'), 
(1, 'Lebrel Afgano'), 
(1, 'Bloodhound'), 
(1, 'Rastreador Inglés'), 
(1, 'Podenco Ibicenco'), 
(1, 'Plott Hound'), 
(1, 'Siberian Husky'), 
(1, 'Keeshond'), 
(1, 'Kelpie'), 
(1, 'Komondor'), 
(1, 'Kuvasz'), 
(1, 'Labradoodle'), 
(1, 'Labrador Retriever'), 
(1, 'Leonberger'), 
(1, 'Lhasa Apso'), 
(1, 'Alaskan Malamute'), 
(1, 'Pastor Belga Malinois'), 
(1, 'Bichón Maltés'), 
(1, 'Bullmastiff'), 
(1, 'Mastín Inglés'), 
(1, 'Mastín Tibetano'), 
(1, 'Xoloitzcuintle'), 
(1, 'Mestizo / Criollo'), 
(1, 'Boyero de Berna'), 
(1, 'Gran Boyero Suizo'), 
(1, 'Terranova'), 
(1, 'Otterhound'), 
(1, 'Pastor del Cáucaso'), 
(1, 'Papillon'), 
(1, 'Pekinés'), 
(1, 'Corgi Pembroke'), 
(1, 'Pinscher Miniatura'), 
(1, 'Pitbull'), 
(1, 'Pointer Alemán'), 
(1, 'Pointer Alemán de Pelo Largo'), 
(1, 'Pomerania'), 
(1, 'Caniche Mediano'), 
(1, 'Caniche Miniatura'), 
(1, 'Caniche Estándar'), 
(1, 'Caniche Toy'), 
(1, 'Pug / Carlino'), 
(1, 'Puggle'), 
(1, 'Puli'), 
(1, 'Pumi'), 
(1, 'Gran Pirineo'), 
(1, 'Redbone Coonhound'), 
(1, 'Retriever de Chesapeake'), 
(1, 'Retriever de Pelo Rizado'), 
(1, 'Retriever de Pelo Liso'), 
(1, 'Golden Retriever'), 
(1, 'Crestado Rodeniano'), 
(1, 'Rottweiler'), 
(1, 'Saluki'), 
(1, 'Samoyedo'), 
(1, 'Schipperke'), 
(1, 'Schnauzer Gigante'), 
(1, 'Schnauzer Miniatura'), 
(1, 'Sabueso Italiano'), 
(1, 'Setter Inglés'), 
(1, 'Setter Gordon'), 
(1, 'Setter Irlandés'), 
(1, 'Shiba Inu'), 
(1, 'Shih Tzu'), 
(1, 'Cavalier King Charles'), 
(1, 'Bretón'), 
(1, 'Cocker Spaniel'), 
(1, 'Spaniel de Agua Irlandés'), 
(1, 'Spaniel Japonés'), 
(1, 'Sussex Spaniel'), 
(1, 'Springer Spaniel Galés'), 
(1, 'Springer Spaniel Inglés'), 
(1, 'San Bernardo'), 
(1, 'American Terrier'), 
(1, 'Terrier Australiano'), 
(1, 'Terrier Bedlington'), 
(1, 'Terrier Border'), 
(1, 'Fox Terrier'), 
(1, 'Terrier Irlandés'), 
(1, 'Terrier Azul de Kerry'), 
(1, 'Terrier de Norfolk'), 
(1, 'Terrier de Norwich'), 
(1, 'Patterdale Terrier'), 
(1, 'Jack Russell Terrier'), 
(1, 'Terrier Escocés'), 
(1, 'Terrier Tibetano'), 
(1, 'Terrier Galés'), 
(1, 'West Highland White Terrier'), 
(1, 'Tervueren'), 
(1, 'Vizsla'), 
(1, 'Perro de Agua Español'), 
(1, 'Weimaraner'), 
(1, 'Whippet'), 
(1, 'Cazador de Lobos Irlandés');

INSERT INTO razas (especie_id, raza) VALUES 
(2, 'Mestizo / Común Europeo'),
(2, 'Raza No Identificada / Otra'),
(2, 'Abisinio'), 
(2, 'Egeo'), 
(2, 'Bobtail Americano'), 
(2, 'Curl Americano'), 
(2, 'American Shorthair'), 
(2, 'Pelo de Alambre Americano'), 
(2, 'Mau Arábigo'), 
(2, 'Mist Australiano'), 
(2, 'Balinés'), 
(2, 'Bambino'), 
(2, 'Bengalí'), 
(2, 'Sagrado de Birmania'), 
(2, 'Bombay'), 
(2, 'Británico de Pelo Largo'), 
(2, 'Británico de Pelo Corto'), 
(2, 'Birmano'), 
(2, 'Burmilla'), 
(2, 'California Spangled'), 
(2, 'Chantilly-Tiffany'), 
(2, 'Chartreux (Cartujo)'), 
(2, 'Chausie'), 
(2, 'Cheetoh'), 
(2, 'Colorpoint Shorthair'), 
(2, 'Cornish Rex'), 
(2, 'Cymric'), 
(2, 'Devon Rex'), 
(2, 'Donskoy'), 
(2, 'Dragon Li'), 
(2, 'Mau Egipcio'), 
(2, 'Exótico de Pelo Corto'), 
(2, 'Habana Brown'), 
(2, 'Himalayo'), 
(2, 'Bobtail Japonés'), 
(2, 'Javanés'), 
(2, 'Khao Manee'), 
(2, 'Korat'), 
(2, 'Bobtail Kuriliana'), 
(2, 'LaPerm'), 
(2, 'Maine Coon'), 
(2, 'Malayo'), 
(2, 'Manx'), 
(2, 'Munchkin'), 
(2, 'Nebelung'), 
(2, 'Bosque de Noruega'), 
(2, 'Ocicat'), 
(2, 'Oriental'), 
(2, 'Persa'), 
(2, 'Pixie Bob'), 
(2, 'Ragamuffin'), 
(2, 'Ragdoll'), 
(2, 'Azul Ruso'), 
(2, 'Savannah'), 
(2, 'Scottish Fold'), 
(2, 'Selkirk Rex'), 
(2, 'Siamés'), 
(2, 'Siberiano'), 
(2, 'Singapur'), 
(2, 'Snowshoe'), 
(2, 'Somalí'), 
(2, 'Esfinge / Sphynx'), 
(2, 'Tonkinés'), 
(2, 'Toyger'), 
(2, 'Angora Turco'), 
(2, 'Van Turco'), 
(2, 'York Chocolate'),
(2, 'Doméstico de Pelo Corto');

INSERT INTO estados_paciente (estado, descripcion) VALUES
('Pre-registrado', 'El paciente está agendado o ingresado en el sistema de una sucursal, pero no tiene visibilidad del historial médico anterior por razones de privacidad.'),
('Activo', 'El paciente fue admitido a la clinica y la clinica tiene acceso a el historial clinico del paciente.'),
('Inactivo', 'La clinica no tiene acceso a la informacion del paciente.');

INSERT INTO motivos_cita (motivo, descripcion) VALUES
('Consulta General', 'Evaluación médica de rutina o chequeo preventivo.'),
('Vacunación', 'Aplicación de inmunizaciones y control de pasaporte sanitario.'),
('Cirugía', 'Procedimientos quirúrgicos programados.'),
('Urgencia', 'Atención médica inmediata por compromiso de salud.');

INSERT INTO estados_cita (estado, descripcion) VALUES
('Agendada', 'Turno planificado en la agenda del profesional sin confirmación aún.'),
('Confirmada', 'Turno validado por el propietario o el personal de la clínica.'),
('Cancelada', 'Turno anulado previamente a la fecha y hora programada.'),
('No-Show', 'El paciente no se presentó al evento clínico programado.');

INSERT INTO tipos_relacion (tipo, descripcion) VALUES
('Tutor Principal', 'Persona legalmente responsable del animal y firmante de consentimientos.'),
('Co-propietario', 'Familiar, pareja o persona autorizada con acceso a la historia clínica.'),
('Contacto de Emergencia', 'Persona que puede traer a la mascota pero no toma decisiones médicas de costo.'),
('Tutor Temporal', 'Refugio, hogar de tránsito o paseador/cuidador temporal.');

INSERT INTO tipos_tratamiento (tipo, descripcion) VALUES
('Medicamento', 'Indicación farmacológica estándar ligada obligatoriamente al vademécum de la clínica.'),
('Procedimiento Físico', 'Curaciones, vendajes, manejos directos en la clínica o indicaciones conductuales.'),
('Cirugía', 'Intervenciones quirúrgicas derivadas de la evolución clínica de la consulta.'),
('Dieta', 'Prescripciones de soporte nutricional, regímenes alimenticios o alimentos medicados.'),
('Fisioterapia', 'Planes de rehabilitación física, ejercicios complejos o terapias de recuperación.');
